package backend.SecurityLayer.Authen;

import jakarta.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;

@Embeddable
public class AccountFilterId implements Serializable {

    // Matches the field name in the AccountEntity primary key
    private Long accountId;

    // Matches the field name in the UrlEntity primary key
    private Long urlId;

    // Constructors, Getters, Setters (omitted for brevity, typically generated by Lombok/IDE)

    // CRUCIAL: Must override equals() and hashCode() for a composite key
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AccountFilterId that = (AccountFilterId) o;
        return Objects.equals(accountId, that.accountId) &&
                Objects.equals(urlId, that.urlId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accountId, urlId);
    }
}